name = "IDEDelay"
uuid = "82e514b0-3f6c-45fa-b22d-a920b2bad0fe"
authors = ["YukNakata <yunayuna.na@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
